[package]
name = "autodiffmacros"
version = "0.1.0"
authors = ["maximumg9 <maximumg999@gmail.com>"]
description = "The macros for a crate for automatic gradients"
keywords = ["template", "proc_macro", "procmacro"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = "1.0"
syn = { version = "2.0.117", features = ["full"]}
autodiff = {path = ".." }
num = "0.4.3"
rand = "0.10.1"